const nationArr = ['汉族', '蒙古族', '回族', '藏族', '维吾尔族', '苗族', '彝族', '壮族', '布依族', '朝鲜族', '满族', '侗族', '瑶族', '白族', '土家族', '哈尼族', '哈萨克族', '傣族', '黎族', '傈僳族', '佤族', '畲族', '拉祜族', '水族', '东乡族', '纳西族', '景颇族', '柯尔克孜族', '土族', '达斡尔族', '仫佬族', '羌族', '布朗族', '撒拉族', '毛南族', '仡佬族', '锡伯族', '阿昌族', '普米族', '塔吉克族', '怒族', '乌兹别克族', '俄罗斯族', '鄂温克族', '德昂族', '保安族', '裕固族', '京族', '塔塔尔族', '独龙族', '鄂伦春族', '赫哲族', '门巴族', '珞巴族', '基诺族', '高山族'];

const nation = {};
nationArr.forEach((elem, index) => {
  nation[`___${elem}`] = elem;
  nation[`${elem}`] = index;
});

const gender = {
  MALE: 1,
  ___MALE: '男',
  FEMALE: 2,
  ___FEMALE: '女',
};

export default {
  NATION: nation,
  GENDER: gender,
  TEACHER: {
    GENDER: gender,
    WORK_TYPE: {
      FULL_TIME: 1,
      ___FULL_TIME: '全职',
      PART_TIME: 2,
      ___PART_TIME: '兼职',
      COOPERATION: 3,
      ___COOPERATION: '合作',
      ASSISTANT: 4,
      ___ASSISTANT: '助教',
    },
    IS_BELONG: {
      YES: 1,
      ___YES: '是',
      NO: 0,
      ___NO: '否（合作办学）',
    },
    IS_AVAILABLE: {
      YES: 1,
      ___YES: '是',
      NO: 0,
      ___NO: '否',
    },
    EDU_QUALIFICATION: {
      PRIMARY: 1,
      ___PRIMARY: '小学',
      JUNIOR: 2,
      ___JUNIOR: '初中',
      TECHNICAL: 3,
      ___TECHNICAL: '中专',
      SENIOR: 4,
      ___SENIOR: '高中',
      JUNIOR_COLLEGE: 5,
      ___JUNIOR_COLLEGE: '专科',
      COLLEGE: 6,
      ___COLLEGE: '本科',
      MASTER: 7,
      ___MASTER: '硕士研究生',
      DOCTOR: 8,
      ___DOCTOR: '博士研究生',
      POSTDOCTOR: 9,
      ___POSTDOCTOR: '博士后',
    },
    POLITICAL_FACE: {
      ZHONG_GONG: 1,
      ___ZHONG_GONG: '中共党员',
      YU_BEI: 2,
      ___YU_BEI: '中共预备党员',
      TUAN: 3,
      ___TUAN: '共青团员',
      MIN_GE: 4,
      ___MIN_GE: '民革党员',
      MIN_MENG: 5,
      ___MIN_MENG: '民盟盟员',
      MIN_JIAN: 6,
      ___MIN_JIAN: '民建会员',
      MIN_JIN: 7,
      ___MIN_JIN: '民进会员',
      NONG_GONG: 8,
      ___NONG_GONG: '农工党党员',
      ZHI_GONG: 9,
      ___ZHI_GONG: '致公党党员',
      JIU_SAN: 10,
      ___JIU_SAN: '九三学社社员',
      TAI_MENG: 11,
      ___TAI_MENG: '台盟盟员',
      NONE: 12,
      ___NONE: '无党派民主人士',
      NORMAL: 13,
      ___NORMAL: '普通公民',
    },
    IS_DISPLAY: {
      YES: 1,
      ___YES: '是',
      NO: 0,
      ___NO: '否',
    },
    IS_INDEX_SHOW: {
      YES: 1,
      ___YES: '是',
      NO: 0,
      ___NO: '否',
    },
  },
  STUDENT: {
    GENDER: gender,
    SOURCE: {
      UNKNOW: 0,
      ___UNKNOW: '未设置',
      AD: 1,
      ___AD: '户外广告',
      POST: 2,
      ___POST: '宣传单',
      FRIEND: 3,
      ___FRIEND: '亲友推荐',
      NET: 4,
      ___NET: '微信咨询',
      ACTIVITY: 5,
      ___ACTIVITY: '活动邀约',
      OTHER: 6,
      ___OTHER: '其他',
    },
  },
  WEEK: {
    MONDAY: 1,
    ___MONDAY: '周一',
    TUESDAY: 2,
    ___TUESDAY: '周二',
    WEDNESDAY: 3,
    ___WEDNESDAY: '周三',
    THURSDAY: 4,
    ___THURSDAY: '周四',
    FRIDAY: 5,
    ___FRIDAY: '周五',
    SATURDAY: 6,
    ___SATURDAY: '周六',
    SUNDAY: 7,
    ___SUNDAY: '周日',
  },
};
